# You typically have 1 profile per warehouse.
my-bigquery-wh:
  # This is the name of the default target to use
  target: dev

  outputs:
    # Example using service account keyfile
    # prod:
    #   type: bigquery
    #   method: service-account
    #   project: "{{ env_var('MY_BIGQUERY_WH_PROD_PROJECT') }}"
    #   dataset: "{{ env_var('MY_BIGQUERY_WH_PROD_DATASET') }}"
    #   keyfile: "{{ env_var('MY_BIGQUERY_WH_PROD_KEYFILE') }}"

    # A target named "prod"
    # You typically a target per tier (dev, staging, prod)
    prod:
      type: bigquery
      method: oauth
      project: "{{ env_var('MY_BIGQUERY_WH_DEV_PROJECT') }}"
      dataset: "{{ env_var('MY_BIGQUERY_WH_DEV_DATASET') }}"

    # Another target named "dev"
    # Example using gcloud command
    dev:
      type: bigquery
      method: oauth
      project: "{{ env_var('MY_BIGQUERY_WH_DEV_PROJECT') }}"
      dataset: "{{ env_var('MY_BIGQUERY_WH_DEV_DATASET') }}"
