models:
  - name: stg_jaffle_shop_2__customers
    columns:
      - name: id
        tests:
          - unique
          - not_null
  - name: stg_jaffle_shop_2__orders
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: customer_id
        tests:
          - relationships:
              to: ref('stg_jaffle_shop_2__customers')
              field: id
  - name: stg_stripe_2__payments
    columns:
      - name: id
        tests:
          - unique
          - not_null
      - name: order_id
        tests:
          - relationships:
              to: ref('stg_jaffle_shop_2__orders')
              field: id
      - name: status
        tests:
          - accepted_values:
              values:
                - success
                - fail

sources:
  - name: jaffle_shop_2
    database: "{{ env_var('MY_BIGQUERY_WH_DEV_PROJECT') }}"
    schema: "{{ env_var('MY_BIGQUERY_WH_DEV_DATASET') }}"
    tables:
      - name: orders
        columns:
          - name: id
            description: primary key of orders table
            tests:
              - unique
              - not_null
          - name: user_id
            tests:
              - relationships:
                  to: ref('customers')
                  field: id
      - name: customers
        columns:
          - name: id
            tests:
              - unique
              - not_null
  - name: stripe_2
    database: "{{ env_var('MY_BIGQUERY_WH_DEV_PROJECT') }}"
    schema: "{{ env_var('MY_BIGQUERY_WH_DEV_DATASET') }}"
    tables:
      - name: payments
        columns:
          - name: id
            description: primary key of orders table
            tests:
              - unique
              - not_null
          - name: orderid
            tests:
              - relationships:
                  to: ref('orders')
                  field: id
          - name: status
            tests:
              - accepted_values:
                  values:
                    - success
                    - fail
