version: 2
models:
  - name: stg_customers
    columns: 
      - name: customer_id
        tests:
          - unique
          - not_null
  - name: stg_orders
    columns:
      - name: order_id
        tests:
          - unique
          - not_null
      - name: status
        tests:
          - accepted_values:
              values:
                - completed
                - shipped
                - returned
                - return_pending
                - placed
      - name: customer_id
        tests:
          - relationships:
              to: ref('stg_customers')
              field: customer_id
sources:
  - name: jaffle_shop
    database: dbt-tutorial
    schema: jaffle_shop
    tables:
      - name: customers
      - name: orders
        # dbt source freshness will look at the max(orders._etl_loaded_at)
        # and issue a warning if over 12 hours old or an error if over 24 hours old
        freshness:
          warn_after:
            count: 12
            period: hour
          error_after:
            count: 24
            period: hour
        loaded_at_field: _etl_loaded_at
